services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Mohanish7777777/PYRO-RENAME-BOT.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: true
      - key: API_ID 
        sync: true
      - key: API_HASH
        sync: true
      - key: WEBHOOK
        synv: false 
      - key: FORCE_SUB 
        sync: false
      - key: DB_NAME 
        sync: true
      - key: DB_URL 
        sync: true 
      - key: START_PIC 
        sync: true
      - key: ADMIN 
        sync: false    
    autoDeploy: false 
