services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Mohanish7777777/PYRO-RENAME-BOT.git      
    branch: main
    envVars:
      - key: BOT_TOKEN
        value: 6132728857:AAHX16VnWQl1fqto91_7M4H8eQ6IxCkI9cs
        sync: true
      - key: API_ID 
        value: 20244111
        sync: true
      - key: API_HASH
        value: b76d27da2a4220fe109fe9ef0e866530
        sync: true
      - key: WEBHOOK
        value: true
        sync: true
      - key: FORCE_SUB 
        value: https://t.me/xadmin_bots
        sync: true
      - key: DB_NAME
        value: musicdb
        sync: true
      - key: DB_URL 
        value: mongodb+srv://kfakeid9:Jobijobi1@musicdb.urlvere.mongodb.net/?retryWrites=true&w=majority
        sync: true
      - key: START_PIC
        value: https://telegra.ph/file/aa1faf8dafa22f4a9ce48.jpg
        sync: true
      - key: ADMIN 
        sync: false    
    autoDeploy: false 
